In [1]:
import sys, os, glob, pickle, toml, json
import pickle
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.cm as cm
import cartopy.crs as ccrs
import cartopy.feature as cfeature

def set_background(ax):
    ax.set_extent([-121, -72, 25, 50])

    # Background boundaries
    # ax.add_feature(cfeature.LAND)
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(cfeature.BORDERS)
    states_provinces = cfeature.NaturalEarthFeature(
        category='cultural',
        name='admin_1_states_provinces_lines',
        scale='50m',
        facecolor='none')
    ax.add_feature(states_provinces, edgecolor='gray')
    
    return ax


def cal_ratio_within_bins(data, bins):
    binsc = np.zeros(len(bins)-1)
    ratio = np.zeros(len(bins)-1)
    for i in range(len(bins)-1):
        indi = (data>bins[i]) & (data<=bins[i+1])
        ratio[i] = np.sum(indi)/np.sum(~np.isnan(data))
        binsc[i] = (bins[i]+bins[i+1])/2
    return binsc, ratio

In [2]:
# load info
infile_basin_info = f"/glade/work/guoqiang/CTSM_CAMELS/data_mesh_surf/HillslopeHydrology/CAMELS_level1_basin_info.csv"
df_info = pd.read_csv(infile_basin_info)

In [5]:
# input/out and iteration information
iternum = 5
inpath_moasmo = '/glade/campaign/cgd/tss/people/guoqiang/CTSM_CAMELS_proj/Calib_HH_MOASMO_bigrange/'
outpath = f'/glade/campaign/cgd/tss/people/guoqiang/CTSM_CAMELS_proj/Calib_HH_MOASMO_bigrange/LargeSampleEmulator_exps_out'

In [9]:
    df_lse_metric = []

    for tarbasin in range(len(df_info)):
    # for tarbasin in range(5):
        for i in range(iternum):
            infile = f'{inpath_moasmo}/level1_{tarbasin}_MOASMOcalib/ctsm_outputs_emutest/iter{i}_many_metric.csv'    
            dfi = pd.read_csv(infile)
            dfi['basin'] = tarbasin
            dfi['iter'] = i
            dfi['trial'] = np.arange(len(dfi))
            if len(df_lse_metric) == 0:
                df_lse_metric = dfi
            else:
                df_lse_metric = pd.concat([df_lse_metric, dfi])

In [10]:
metname = 'kge'
met_stats_lse = np.nan * np.zeros([len(df_info), iternum, 3]) # best; mean; median
for i in range(iternum):
    indi = (df_lse_metric['iter']==i)
    for j in range(len(df_info)):
        indij = indi & (df_lse_metric['basin']==j)
        dij = df_lse_metric[indij][metname].values

        met_stats_lse[j, i, 0] = np.nanmax(dij)
        met_stats_lse[j, i, 1] = np.nanmean(dij)
        met_stats_lse[j, i, 2] = np.nanmedian(dij)


In [14]:
np.nanmedian(met_stats_lse[:,:,0], axis=0)

array([0.46116677, 0.50478524, 0.51495102, 0.52538579, 0.53496219])

In [16]:
import xarray as xr
file = '/glade/work/guoqiang/CTSM_CAMELS/data_mesh_surf/HillslopeHydrology/sfcdata/surfdata_CAMELSandTDX_areabias_fix.simp0.001.level1_hist_78pfts_CMIP6_simyr2000_HAND_4_col_hillslope_geo_params_nlcd_bedrock.nc'
dssurf = xr.load_dataset(file)

In [35]:
index = dssurf.zbedrock.values < 2
np.nanmedian(met_stats_lse[index,:,0], axis=0)

array([0.46294301, 0.50886277, 0.51978451, 0.52679177, 0.53708631])

In [41]:
met_stats_lse[100,:,0]

array([0.61060931, 0.62978756, 0.63255254, 0.63223743, 0.63592718])

In [42]:
dssurf.zbedrock.values[221]

1.1706964562472866

In [45]:
df_info.iloc[221]

hru_id                                                     3384450
ann_P                                                          0.0
lon_cen                                                  -88.52769
lat_cen                                                   37.53076
AREA                                                 112284035.644
elev_mean                                                191.72973
ave_T                                                          NaN
july_T                                                         NaN
Perimeter                                                    77775
Source                                                       HSTDX
latoutlet                                                 37.47227
lonoutlet                                                -88.54727
areaUSGS                                                    111.13
RawCAMELSarea                                           112.284036
RawTDXarea                                              113.72

In [46]:
pd.read_csv('/glade/work/guoqiang/CTSM_CAMELS/data_paramcailb/ParamCalib_basinparam_3384450.csv')

Unnamed: 0                                    Type  \
0            0                               Hydrology   
1            1                               Hydrology   
2            2                               Hydrology   
3            3                               Hydrology   
4            4  Stomatal resistance and photosynthesis   
5            5                               Hydrology   
6            6                               Hydrology   
7            7                          Snow Processes   
8            8                               Hydrology   
9            9                               Hydrology   
10          10                          Snow Processes   
11          11  Stomatal resistance and photosynthesis   
12          12                               Hydrology   
13          13  Stomatal resistance and photosynthesis   
14          14                               Hydrology   
15          15                         Biogeochemistry   
16          16         Sensible and Latent Heat Fluxes   

                         Process  PPE_DailyQ_Rank  \
0                   Infiltration                0   
1   Infiltration\r\nSoil storage                1   
2           Soil water drainage                10   
3         Soil storage capacity                11   
4             ET (transpiration)                2   
5                   Infiltration               23   
6         Soil storage capacity                 9   
7               Snowpack physics               35   
8            Canopy Interception               45   
9                   Canopy Water               13   
10              Snowpack physics               17   
11              Plant hydraulics               15   
12         Surface Water Storage               30   
13                Photosynthesis               16   
14           Baseflow generation               37   
15                  Plant growth               14   
16            ET (transpiration)               22   

                       Parameter  Default_glob    Lower_glob    Upper_glob  \
0                           FMAX  3.816694e-01  1.908347e-01  5.725041e-01   
1                            fff  5.000000e-01  2.000000e-02  5.000000e+00   
2                       hksat_sf  1.000000e+00  1.000000e-01  1.000000e+01   
3                      sucsat_sf  1.000000e+00  1.000000e-01  1.000000e+01   
4                    medlynslope  4.840380e+00  2.420190e+00  7.260570e+00   
5                          e_ice  6.000000e+00  1.000000e-01  8.000000e+00   
6                      watsat_sf  1.000000e+00  2.500000e-01  2.000000e+00   
7      upplim_destruct_metamorph  1.750000e+02  1.000000e+01  5.000000e+02   
8          interception_fraction  1.000000e+00  1.000000e-01  1.000000e+00   
9   maximum_leaf_wetted_fraction  5.000000e-02  1.000000e-02  5.000000e-01   
10                          zsno  7.750000e-04  1.000000e-05  7.000000e-02   
11                          kmax  1.910000e-08  2.270000e-09  3.790000e-08   
12                     slopebeta -3.000000e+00 -1.000000e+01 -5.000000e-01   
13                        jmaxb0  3.110000e-02  1.000000e-02  5.000000e-02   
14                    n_baseflow  1.000000e+00  2.000000e-01  5.000000e+00   
15                        leafcn  2.224729e+01  1.112365e+01  3.337094e+01   
16                            cv  1.000000e-02  2.500000e-03  4.000000e-02   

       Lower_raw     Upper_raw            LowUp_vsPPE    Source  Binding  \
0   1.000000e-01  9.000000e-01               NotInPPE  Surfdata      NaN   
1   2.000000e-02  5.000000e+00                   Same     Param      NaN   
2   1.000000e-01  1.000000e+01                   Same     Param      NaN   
3   1.000000e-01  1.000000e+01                   Same     Param      NaN   
4   3.235949e+00  6.934051e+00            BiggerRange     Param      NaN   
5   1.000000e-01  8.000000e+00              Low0to0.1     Param      NaN   
6   8.000000e-01  1.200000e+00            BiggerRange     Param    