In [5]:
import pandas as pd
import numpy as np

In [94]:
def read_parameter_csv(file_parameter_list):
    df_calibparam = pd.read_csv(file_parameter_list)

    if isinstance(df_calibparam.iloc[0]['Upper'], str):
        for c in ['Upper', 'Lower']:
            arr = []
            for i in range(len(df_calibparam)):
                vi = df_calibparam.iloc[i][c]
                if ',' in vi:
                    arr.append(np.array(vi.split(',')).astype(np.float64))
                else:
                    arr.append(np.array([np.float64(vi)]))
            df_calibparam[c] = arr
    return df_calibparam

df = read_parameter_csv('param_ASG_20221206_moasmo.csv')
df['Upper'].values

array([array([250000.]), array([2.]), array([-0.5]), array([10.]),
       array([8.]), array([4.]), array([0.1]), array([0.8]), array([9.]),
       array([0.0e+00, 2.5e-10, 2.9e-10, 1.6e-10, 1.9e-08, 5.1e-10, 1.0e-08,
              1.6e-10, 2.1e-10, 1.7e-09, 1.1e-07, 1.5e-10, 1.9e-10, 5.9e-08,
              1.0e-07, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
              3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
            

In [108]:
len(df['Upper'].values)

18

In [90]:
df.loc[df['Parameter']=='krmax']['Lower'].iloc[0]

array([0.0e+00, 2.3e-11, 2.6e-11, 2.8e-11, 1.1e-10, 5.4e-11, 8.0e-11,
       6.9e-11, 9.3e-11, 4.5e-11, 7.4e-11, 2.2e-11, 1.0e-11, 4.7e-11,
       8.2e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11, 6.0e-11,
       6.0e-11, 6.0e-11])

In [109]:
a = {'a': 12, 'b': np.array([12, 31212])}

In [117]:
np.savez_compressed('test.npz',a=a)

In [134]:
s=pd.read_csv('test.csv').iloc[9]['Upper']

In [143]:
s.replace('\n', '')

'[0.0e+00 2.5e-10 2.9e-10 1.6e-10 1.9e-08 5.1e-10 1.0e-08 1.6e-10 2.1e-10 1.7e-09 1.1e-07 1.5e-10 1.9e-10 5.9e-08 1.0e-07 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09 3.8e-09]'

In [140]:
elements = s.strip('[]').split()

# Convert elements to float and create a NumPy array
array = np.array(elements, dtype=float)

In [141]:
array

array([0.0e+00, 2.5e-10, 2.9e-10, 1.6e-10, 1.9e-08, 5.1e-10, 1.0e-08,
       1.6e-10, 2.1e-10, 1.7e-09, 1.1e-07, 1.5e-10, 1.9e-10, 5.9e-08,
       1.0e-07, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09, 3.8e-09,
       3.8e-09, 3.8e-09])

In [158]:
df = pd.DataFrame([[1,2]], columns=['m1','m2'])
# df.to_csv('test.csv')
df

m1  m2
0   1   2

In [150]:
pd.read_csv('test.csv')

Unnamed: 0  metric
0      kge_q     0.1
1     rmse_q     0.2

In [33]:
d = df['Lower'].values

In [34]:
np.array(d[0].split(',')).astype(np.float64)

array([20000.])

In [70]:
# Create a dictionary with sample data
data = {
    'Name': ['John', 'Emily', 'Ryan', 'Sophia'],
    'Age': [ [1], [2], [3], [4]],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 55000]
}

# Create the DataFrame
df = pd.DataFrame(data)

In [71]:
df

Name  Age      City  Salary
0    John  [1]  New York   50000
1   Emily  [2]     Paris   60000
2    Ryan  [3]    London   70000
3  Sophia  [4]     Tokyo   55000

In [159]:
df_info

NameError: name 'df_info' is not defined

In [162]:
np.log(0)

/var/folders/pf/n30tfn0j0n93dr81jm369hyc0000gp/T/ipykernel_20851/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

Name  Age      City  Salary  as
0    John  [1]  New York   50000   1
1   Emily  [2]     Paris   60000   1
2    Ryan  [3]    London   70000   1
3  Sophia  [4]     Tokyo   55000   1