In [2]:
# we may need to change target variables after creating cases
import numpy as np
import xarray as xr
import glob, os, sys

In [3]:
"hist_fincl2 = 'QRUNOFF','H2OSNO','ZWT','SOILWATER_10CM','EFLX_LH_TOT','QDRAI','QOVER','RAIN'"


"hist_fincl2 = 'QRUNOFF','H2OSNO','ZWT','SOILWATER_10CM','EFLX_LH_TOT','QDRAI','QOVER','RAIN'"

In [4]:
# h0
basin = 'level1_60'
path = '/glade/work/guoqiang/CTSM_cases/CAMELS_Calib/Calib_all_HH_MOASMO'
files = glob.glob(f'{path}/{basin}_SpinupFiles/archive/lnd/hist/*.clm2.h0.*.nc')
files.sort()
ds = xr.open_dataset(files[0])
ds

<xarray.Dataset>
Dimensions:                        (levgrnd: 25, levsoi: 20, levlak: 10,
                                    levdcmp: 1, time: 1, hist_interval: 2,
                                    lndgrid: 1, cft: 64, glc_nec: 10, ltype: 9,
                                    natpft: 15, nvegwcs: 4)
Coordinates:
  * levgrnd                        (levgrnd) float32 0.01 0.04 ... 28.87 42.0
  * levsoi                         (levsoi) float32 0.01 0.04 0.09 ... 6.94 8.03
  * levlak                         (levlak) float32 0.05 0.6 2.1 ... 34.33 44.78
  * levdcmp                        (levdcmp) float32 1.0
  * time                           (time) object 1951-02-01 00:00:00
Dimensions without coordinates: hist_interval, lndgrid, cft, glc_nec, ltype,
                                natpft, nvegwcs
Data variables: (12/261)
    mcdate                         (time) int32 ...
    mcsec                          (time) int32 ...
    mdcur                          (time) int32 ...
    mscur                          (time) int32 ...
    nstep                          (time) int32 ...
    time_bounds                    (time, hist_interval) object ...
    ...                             ...
    WBT_R                          (time, lndgrid) float32 ...
    WBT_U                          (time, lndgrid) float32 ...
    WIND                           (time, lndgrid) float32 ...
    ZBOT                           (time, lndgrid) float32 ...
    ZWT                            (time, lndgrid) float32 ...
    ZWT_PERCH                      (time, lndgrid) float32 ...
Attributes: (12/99)
    title:                                CLM History file information
    comment:                              NOTE: None of the variables are wei...
    Conventions:                          CF-1.0
    history:                              created on 11/29/23 15:52:37
    source:                               Community Terrestrial Systems Model
    hostname:                             cheyenne
    ...                                   ...
    cft_irrigated_switchgrass:            60
    cft_tropical_corn:                    61
    cft_irrigated_tropical_corn:          62
    cft_tropical_soybean:                 63
    cft_irrigated_tropical_soybean:       64
    time_period_freq:                     month_1

In [8]:
ds.QFLX_EVAP_TOT.values 

array([[1.1702859]], dtype=float32)

In [12]:
ds.SNOWLIQ.values

array([[1.0096116]], dtype=float32)

In [19]:
ds.H2OSNO.values

array([[58.852303]], dtype=float32)

In [17]:
ds.SNOW_DEPTH.values

array([[0.20698124]], dtype=float32)